-- ============================================================
-- Ounce (أونصة) — seed data
-- Chart of accounts transcribed verbatim from src/core/chart.js
-- (CHART_OF_ACCOUNTS). Run this once, right after schema.sql,
-- against the same database.
-- ============================================================

insert into accounts (code, name, parent_code, unit, nature, statement, is_group, pool, method) values
  ('1000', 'الأصول', NULL, 'both', 'debit', 'balance', true, NULL, NULL),
  ('1100', 'النقدية وما في حكمها', '1000', 'currency', 'debit', 'balance', true, NULL, NULL),
  ('1110', 'الخزنة — نقدي', '1100', 'currency', 'debit', 'balance', false, 'safe', 'cash'),
  ('1120', 'الخزنة — شبكة', '1100', 'currency', 'debit', 'balance', false, 'safe', 'network'),
  ('1130', 'الصندوق اليومي — نقدي', '1100', 'currency', 'debit', 'balance', false, 'daily', 'cash'),
  ('1140', 'الصندوق اليومي — شبكة', '1100', 'currency', 'debit', 'balance', false, 'daily', 'network'),
  ('1150', 'عهدة شراء الكسر', '1100', 'currency', 'debit', 'balance', false, 'custody', 'cash'),
  ('1200', 'مخزون الذهب', '1000', 'both', 'debit', 'balance', true, NULL, NULL),
  ('1210', 'ذهب مشغول — جاهز للبيع', '1200', 'both', 'debit', 'balance', false, NULL, NULL),
  ('1220', 'ذهب خام بالخزنة', '1200', 'both', 'debit', 'balance', false, NULL, NULL),
  ('1225', 'خزنة الكسر — ذهب مُصفّى', '1200', 'gram', 'debit', 'balance', false, NULL, NULL),
  ('1230', 'كسر — بانتظار التصفية', '1200', 'both', 'debit', 'balance', false, NULL, NULL),
  ('1240', 'ذهب لدى مكاتب التسكير', '1200', 'both', 'debit', 'balance', false, NULL, NULL),
  ('1300', 'المدينون', '1000', 'currency', 'debit', 'balance', true, NULL, NULL),
  ('1310', 'عملاء — مبيعات آجلة', '1300', 'currency', 'debit', 'balance', false, NULL, NULL),
  ('1320', 'موردون — رصيد مدين', '1300', 'both', 'debit', 'balance', false, NULL, NULL),
  ('1330', 'سلف وعُهد الموظفين', '1300', 'currency', 'debit', 'balance', false, NULL, NULL),
  ('1350', 'ذهب لدى فروع أخرى', '1300', 'both', 'debit', 'balance', false, NULL, NULL),
  ('1340', 'مكاتب تسكير — رصيد مدين', '1300', 'both', 'debit', 'balance', false, NULL, NULL),
  ('2000', 'الالتزامات', NULL, 'both', 'credit', 'balance', true, NULL, NULL),
  ('2100', 'الدائنون', '2000', 'both', 'credit', 'balance', true, NULL, NULL),
  ('2110', 'موردون — ذهب مستحق', '2100', 'gram', 'credit', 'balance', false, NULL, NULL),
  ('2120', 'موردون — أجور مستحقة', '2100', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('2130', 'مكاتب تسكير — التزام', '2100', 'both', 'credit', 'balance', false, NULL, NULL),
  ('2200', 'التزامات أخرى', '2000', 'currency', 'credit', 'balance', true, NULL, NULL),
  ('2210', 'عرابين وحجوزات عملاء', '2200', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('2220', 'ضريبة القيمة المضافة المستحقة', '2200', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('2230', 'رواتب مستحقة', '2200', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('3000', 'حقوق الملكية', NULL, 'both', 'credit', 'balance', true, NULL, NULL),
  ('3100', 'رأس المال', '3000', 'both', 'credit', 'balance', false, NULL, NULL),
  ('3200', 'حسابات الشركاء', '3000', 'both', 'credit', 'balance', false, NULL, NULL),
  ('3300', 'أرباح محتجزة', '3000', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('3400', 'سحوبات الملاك', '3000', 'both', 'debit', 'balance', false, NULL, NULL),
  ('4000', 'الإيرادات', NULL, 'currency', 'credit', 'income', true, NULL, NULL),
  ('4100', 'إيراد المبيعات', '4000', 'currency', 'credit', 'income', true, NULL, NULL),
  ('4110', 'قيمة المعدن المباع', '4100', 'both', 'credit', 'income', false, NULL, NULL),
  ('4120', 'ربح المصنعية والهامش', '4100', 'currency', 'credit', 'income', false, NULL, NULL),
  ('4140', 'إيراد بيع مشغولات', '4100', 'currency', 'credit', 'income', false, NULL, NULL),
  ('4130', 'إيراد الإصلاحات', '4100', 'currency', 'credit', 'income', false, NULL, NULL),
  ('4190', 'مردودات المبيعات', '4100', 'currency', 'debit', 'income', false, NULL, NULL),
  ('4200', 'أرباح رأسمالية', '4000', 'currency', 'credit', 'income', true, NULL, NULL),
  ('4210', 'ربح رأسمالي محقق من السعر', '4200', 'currency', 'credit', 'income', false, NULL, NULL),
  ('4220', 'خسارة رأسمالية محققة', '4200', 'currency', 'debit', 'income', false, NULL, NULL),
  ('4230', 'فرق إعادة تقييم غير محقق', '4200', 'currency', 'credit', 'income', false, NULL, NULL),
  ('4300', 'إيرادات أخرى', '4000', 'currency', 'credit', 'income', true, NULL, NULL),
  ('4310', 'فائض تصفية الكسر', '4300', 'both', 'credit', 'income', false, NULL, NULL),
  ('4320', 'فائض وزن', '4300', 'both', 'credit', 'income', false, NULL, NULL),
  ('4330', 'زيادة بالجرد', '4300', 'currency', 'credit', 'income', false, NULL, NULL),
  ('4390', 'إيرادات متنوّعة', '4300', 'currency', 'credit', 'income', false, NULL, NULL),
  ('4340', 'ذهب مُستخرَج بالإصلاح', '4300', 'both', 'credit', 'income', false, NULL, NULL),
  ('5000', 'تكلفة المبيعات', NULL, 'both', 'debit', 'income', true, NULL, NULL),
  ('5100', 'تكلفة الذهب المباع', '5000', 'both', 'debit', 'income', true, NULL, NULL),
  ('5110', 'مشتريات من الموردين', '5100', 'both', 'debit', 'income', false, NULL, NULL),
  ('5120', 'شراء كسر', '5100', 'both', 'debit', 'income', false, NULL, NULL),
  ('5130', 'شراء سبائك وخام', '5100', 'both', 'debit', 'income', false, NULL, NULL),
  ('5200', 'المصنعية', '5000', 'currency', 'debit', 'income', true, NULL, NULL),
  ('5210', 'أجور الموردين', '5200', 'currency', 'debit', 'income', false, NULL, NULL),
  ('5220', 'مصنعية تصنيع من كسر', '5200', 'currency', 'debit', 'income', false, NULL, NULL),
  ('5230', 'إعدام مصنعية عند الصهر', '5200', 'currency', 'debit', 'income', false, NULL, NULL),
  ('5300', 'الفاقد والهالك', '5000', 'both', 'debit', 'income', true, NULL, NULL),
  ('5310', 'هالك تصنيع', '5300', 'both', 'debit', 'income', false, NULL, NULL),
  ('5320', 'ذهب مُضاف بالإصلاح', '5300', 'both', 'debit', 'income', false, NULL, NULL),
  ('5330', 'عجز بالجرد', '5300', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6000', 'المصروفات التشغيلية', NULL, 'currency', 'debit', 'income', true, NULL, NULL),
  ('6100', 'الإيجارات', '6000', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6200', 'الرواتب والأجور', '6000', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6300', 'الفواتير والخدمات', '6000', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6400', 'مشتريات غير ذهبية', '6000', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6500', 'عمولات الشبكة والبنوك', '6000', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6600', 'رسوم حكومية', '6000', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6900', 'مصروفات أخرى', '6000', 'currency', 'debit', 'income', false, NULL, NULL),
  ('1400', 'الأصول الثابتة', '1000', 'currency', 'debit', 'balance', false, NULL, NULL),
  ('1410', 'أثاث وتجهيزات المحل', '1400', 'currency', 'debit', 'balance', false, NULL, NULL),
  ('1420', 'فاترينات وخزائن عرض', '1400', 'currency', 'debit', 'balance', false, NULL, NULL),
  ('1430', 'خزنة حديدية', '1400', 'currency', 'debit', 'balance', false, NULL, NULL),
  ('1440', 'أجهزة وحاسبات وموازين', '1400', 'currency', 'debit', 'balance', false, NULL, NULL),
  ('1450', 'سيارات', '1400', 'currency', 'debit', 'balance', false, NULL, NULL),
  ('1460', 'تحسينات على مأجور', '1400', 'currency', 'debit', 'balance', false, NULL, NULL),
  ('1490', 'مجمّع إهلاك الأصول الثابتة', '1400', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('2300', 'مستحقات الموظفين', '2000', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('2310', 'رواتب مستحقة', '2300', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('2320', 'التأمينات الاجتماعية المستحقة', '2300', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('2330', 'مخصّص نهاية الخدمة', '2300', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('2340', 'عمولات مستحقة', '2300', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('2400', 'حسابات العملاء — أمانة', '2000', 'both', 'credit', 'balance', false, NULL, NULL),
  ('2410', 'أمانة نقدية — أرصدة العملاء', '2400', 'currency', 'credit', 'balance', false, NULL, NULL),
  ('2420', 'أمانة ذهب — أرصدة العملاء', '2400', 'gram', 'credit', 'balance', false, NULL, NULL),
  ('2350', 'سلف موظفين', '2300', 'currency', 'debit', 'balance', false, NULL, NULL),
  ('6700', 'مصروفات الموظفين', '6000', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6710', 'الرواتب الأساسية', '6700', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6720', 'بدل سكن', '6700', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6730', 'بدل مواصلات', '6700', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6740', 'حصة المنشأة في التأمينات', '6700', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6750', 'مصروف نهاية الخدمة', '6700', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6760', 'عمولات البائعين', '6700', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6800', 'مصروف الإهلاك', '6000', 'currency', 'debit', 'income', false, NULL, NULL),
  ('6810', 'خسائر استبعاد أصول', '6000', 'currency', 'debit', 'income', false, NULL, NULL),
  ('7000', 'حسابات نظامية', NULL, 'both', 'debit', 'offBalance', true, NULL, NULL),
  ('7100', 'ذهب أمانة لدى المحل', '7000', 'gram', 'debit', 'offBalance', false, NULL, NULL),
  ('7200', 'بضاعة محجوزة', '7000', 'both', 'debit', 'offBalance', false, NULL, NULL),
  ('7300', 'تحويلات داخلية', '7000', 'both', 'debit', 'offBalance', false, NULL, NULL);

-- Weight-eligible accounts allow-list (WEIGHT_ACCOUNTS in chart.js)
insert into weight_accounts (account_code) values
  ('1210'),
  ('1220'),
  ('1230'),
  ('1240'),
  ('2110'),
  ('7100'),
  ('7200');

-- GOSI rates (from money-rules.js GOSI_RATES)
insert into gosi_rates (nationality, employee_pct, employer_pct) values
  ('saudi', 0.0975, 0.1175),
  ('expat', 0, 0.02);

-- Asset classes (from money-rules.js ASSET_CLASSES)
insert into asset_classes (id, label, account_code, years, salvage_pct) values
  ('furniture', 'أثاث وتجهيزات', '1410', 10, 0.05),
  ('display', 'فاترينات وخزائن عرض', '1420', 8, 0.05),
  ('safe', 'خزنة حديدية', '1430', 15, 0.1),
  ('devices', 'أجهزة وموازين', '1440', 5, 0.0),
  ('vehicle', 'سيارات', '1450', 6, 0.15),
  ('leasehold', 'تحسينات على مأجور', '1460', 5, 0.0);

-- Approval rules (from money-rules.js APPROVAL_RULES)
insert into approval_rules (id, label, threshold, approver_role) values
  ('expense', 'مصروف', 2000, 'manager'),
  ('asset_purchase', 'شراء أصل ثابت', 0, 'manager'),
  ('asset_disposal', 'استبعاد أصل', 0, 'manager'),
  ('payroll_run', 'مسيّر رواتب', 0, 'manager'),
  ('price_change', 'تغيير هامش السعر', 0, 'manager'),
  ('journal_reverse', 'قيد عكسي', 0, 'manager'),
  ('period_close', 'إقفال فترة', 0, 'manager'),
  ('supplier_settle', 'سداد مورد', 10000, 'manager'),
  ('refund', 'ردّ مبلغ', 1000, 'manager');

-- Posting rules (from erp.js POSTING_RULES) — one row per op_type,
-- rule stored as JSONB verbatim (same shape as the JS source object).
insert into posting_rules (op_type, label, rule) values
  ('sale_cash', 'بيع نقدي', '{"label": "بيع نقدي", "cash": {"debit": "1130", "credit": "4140"}, "weight": {"from": "1210", "to": null}}'::jsonb),
  ('sale_card', 'بيع بالشبكة', '{"label": "بيع بالشبكة", "cash": {"debit": "1140", "credit": "4140"}, "weight": {"from": "1210", "to": null}}'::jsonb),
  ('sale_credit', 'بيع آجل', '{"label": "بيع آجل", "cash": {"debit": "1310", "credit": "4140"}, "weight": {"from": "1210", "to": null}}'::jsonb),
  ('sale_partial', 'بيع بالوزن', '{"label": "بيع بالوزن", "cash": {"debit": "1130", "credit": "4140"}, "weight": {"from": "1210", "to": null}}'::jsonb),
  ('sale_return', 'مرتجع بيع', '{"label": "مرتجع بيع", "cash": {"debit": "4140", "credit": "1130"}, "weight": {"from": null, "to": "1210"}}'::jsonb),
  ('network_fee', 'عمولة الشبكة', '{"label": "عمولة الشبكة", "cash": {"debit": "6500", "credit": "1140"}, "weight": null}'::jsonb),
  ('vat_collected', 'ضريبة محصّلة', '{"label": "ضريبة محصّلة", "cash": {"debit": "1130", "credit": "2220"}, "weight": null}'::jsonb),
  ('purchase_cash', 'شراء من مورد نقدًا', '{"label": "شراء من مورد نقدًا", "cash": {"debit": "5110", "credit": "1110"}, "weight": {"from": null, "to": "1210"}}'::jsonb),
  ('purchase_network', 'شراء بالشبكة', '{"label": "شراء بالشبكة", "cash": {"debit": "5110", "credit": "1120"}, "weight": {"from": null, "to": "1210"}}'::jsonb),
  ('purchase_deferred', 'شراء آجل', '{"label": "شراء آجل", "cash": null, "weight": {"from": null, "to": "1210"}, "liability": {"gold": "2110", "fees": "2120"}}'::jsonb),
  ('purchase_office', 'شراء بتسكير مكتب', '{"label": "شراء بتسكير مكتب", "cash": null, "weight": {"from": null, "to": "1210"}, "liability": {"office": "2130"}}'::jsonb),
  ('purchase_scrap_pay', 'شراء مسدَّد بالكسر', '{"label": "شراء مسدَّد بالكسر", "cash": null, "weight": {"from": "1230", "to": "1210"}}'::jsonb),
  ('workmanship_paid', 'أجور المورد', '{"label": "أجور المورد", "cash": {"debit": "5210", "credit": "1110"}, "weight": null}'::jsonb),
  ('scrap_buy', 'شراء كسر', '{"label": "شراء كسر", "cash": {"debit": "5120", "credit": "1150"}, "weight": {"from": null, "to": "1230"}, "stage": "in_box"}'::jsonb),
  ('scrap_send', 'إرسال الكسر للفحص', '{"label": "إرسال الكسر للفحص", "cash": null, "weight": null, "stageChange": {"from": "in_box", "to": "sent"}}'::jsonb),
  ('scrap_assay_gain', 'فائض تقييم', '{"label": "فائض تقييم", "cash": null, "weight": {"from": null, "to": "1230"}, "revenue": "4320"}'::jsonb),
  ('scrap_assay_loss', 'هالك تقييم', '{"label": "هالك تقييم", "cash": null, "weight": {"from": "1230", "to": null}, "cost": "5310"}'::jsonb),
  ('scrap_receive', 'إدخال الكسر للخزنة', '{"label": "إدخال الكسر للخزنة", "cash": null, "weight": null, "stageChange": {"from": "approved", "to": "in_safe"}}'::jsonb),
  ('scrap_to_product', 'تصنيع من كسر', '{"label": "تصنيع من كسر", "cash": {"debit": "5220", "credit": "1110"}, "weight": {"from": "1230", "to": "1210"}}'::jsonb),
  ('product_to_scrap', 'صهر قطعة', '{"label": "صهر قطعة", "cash": null, "weight": {"from": "1210", "to": "1230"}, "cost": "5230"}'::jsonb),
  ('repair_add', 'إضافة وزن بالإصلاح', '{"label": "إضافة وزن بالإصلاح", "cash": null, "weight": {"from": "1230", "to": "1210"}, "cost": "5320"}'::jsonb),
  ('repair_reduce', 'خصم وزن بالإصلاح', '{"label": "خصم وزن بالإصلاح", "cash": null, "weight": {"from": "1210", "to": "1230"}, "revenue": "4340"}'::jsonb),
  ('settle_scrap', 'سداد مورد بالكسر', '{"label": "سداد مورد بالكسر", "cash": null, "weight": {"from": "1230", "to": null}, "liabilityDown": "2110", "guard": "in_safe_only"}'::jsonb),
  ('settle_safe_gold', 'سداد مورد من ذهب الخزنة', '{"label": "سداد مورد من ذهب الخزنة", "cash": null, "weight": {"from": "1220", "to": null}, "liabilityDown": "2110"}'::jsonb),
  ('depreciation', 'إهلاك شهري', '{"label": "إهلاك شهري", "cash": {"debit": "6800", "credit": "1490"}, "weight": null}'::jsonb),
  ('asset_purchase', 'شراء أصل ثابت', '{"label": "شراء أصل ثابت", "cash": {"debit": "1410", "credit": "1110"}, "weight": null}'::jsonb),
  ('asset_disposal', 'استبعاد أصل', '{"label": "استبعاد أصل", "cash": {"debit": "1490", "credit": "1410"}, "weight": null}'::jsonb),
  ('payroll_run', 'مسيّر رواتب', '{"label": "مسيّر رواتب", "cash": {"debit": "6710", "credit": "2310"}, "weight": null}'::jsonb),
  ('payroll_pay', 'صرف الرواتب', '{"label": "صرف الرواتب", "cash": {"debit": "2310", "credit": "1110"}, "weight": null}'::jsonb),
  ('gosi_pay', 'سداد التأمينات', '{"label": "سداد التأمينات", "cash": {"debit": "2320", "credit": "1110"}, "weight": null}'::jsonb),
  ('eos_pay', 'صرف نهاية الخدمة', '{"label": "صرف نهاية الخدمة", "cash": {"debit": "2330", "credit": "1110"}, "weight": null}'::jsonb),
  ('settle_office_gold', 'سداد مكتب بالذهب', '{"label": "سداد مكتب بالذهب", "cash": null, "weight": {"from": "1220", "to": null}, "liabilityMove": {"from": "2130", "to": null}}'::jsonb),
  ('settle_office_cash', 'سداد مكتب نقدًا', '{"label": "سداد مكتب نقدًا", "cash": {"debit": "2130", "credit": "1130"}, "weight": null}'::jsonb),
  ('settle_office', 'سداد بتسكير مكتب', '{"label": "سداد بتسكير مكتب", "cash": null, "weight": null, "liabilityMove": {"from": "2110", "to": "2130"}}'::jsonb),
  ('settle_fees', 'سداد أجور المورد', '{"label": "سداد أجور المورد", "cash": {"debit": "2120", "credit": "1110"}, "weight": null}'::jsonb),
  ('safe_gold_in', 'إدخال ذهب للخزنة', '{"label": "إدخال ذهب للخزنة", "cash": null, "weight": {"from": null, "to": "1220"}}'::jsonb),
  ('safe_gold_out', 'سحب ذهب من الخزنة', '{"label": "سحب ذهب من الخزنة", "cash": null, "weight": {"from": "1220", "to": null}, "requires": "destination"}'::jsonb),
  ('taskir_sell', 'تسكير — بيع خام لمكتب', '{"label": "تسكير — بيع خام لمكتب", "cash": {"debit": "1110", "credit": "5130"}, "weight": {"from": "1220", "to": null}}'::jsonb),
  ('wastage', 'هالك تصنيع', '{"label": "هالك تصنيع", "cash": null, "weight": {"from": "1210", "to": null}, "cost": "5310"}'::jsonb),
  ('weight_surplus', 'فائض وزن', '{"label": "فائض وزن", "cash": null, "weight": {"from": null, "to": "1210"}, "revenue": "4320"}'::jsonb),
  ('audit_missing', 'عجز جرد', '{"label": "عجز جرد", "cash": null, "weight": {"from": "1210", "to": null}, "cost": "5330"}'::jsonb),
  ('expense', 'مصروف تشغيلي', '{"label": "مصروف تشغيلي", "cash": {"debit": "6900", "credit": "1110"}, "weight": null}'::jsonb),
  ('salary', 'راتب', '{"label": "راتب", "cash": {"debit": "6200", "credit": "1110"}, "weight": null}'::jsonb),
  ('rent', 'إيجار', '{"label": "إيجار", "cash": {"debit": "6100", "credit": "1110"}, "weight": null}'::jsonb),
  ('capital_in', 'مساهمة رأس مال', '{"label": "مساهمة رأس مال", "cash": {"debit": "1110", "credit": "3100"}, "weight": null}'::jsonb),
  ('owner_draw', 'سحب مالك', '{"label": "سحب مالك", "cash": {"debit": "3400", "credit": "1110"}, "weight": null}'::jsonb),
  ('customer_deposit', 'عربون', '{"label": "عربون", "cash": {"debit": "1130", "credit": "2210"}, "weight": null}'::jsonb),
  ('repair_income', 'إيراد إصلاح', '{"label": "إيراد إصلاح", "cash": {"debit": "1130", "credit": "4130"}, "weight": null}'::jsonb),
  ('receipt', 'تحصيل آجل', '{"label": "تحصيل آجل", "cash": {"debit": "1130", "credit": "1310"}, "weight": null}'::jsonb),
  ('cash_surplus', 'زيادة جرد', '{"label": "زيادة جرد", "cash": {"debit": "1130", "credit": "4330"}, "weight": null}'::jsonb),
  ('cash_shortage', 'عجز جرد', '{"label": "عجز جرد", "cash": {"debit": "5330", "credit": "1130"}, "weight": null}'::jsonb),
  ('transfer', 'تحويل داخلي', '{"label": "تحويل داخلي", "cash": {"debit": "7300", "credit": "7300"}, "weight": null}'::jsonb),
  ('trust_in', 'استلام ذهب أمانة', '{"label": "استلام ذهب أمانة", "cash": null, "weight": {"from": null, "to": "7100"}}'::jsonb),
  ('trust_out', 'تسليم ذهب أمانة', '{"label": "تسليم ذهب أمانة", "cash": null, "weight": {"from": "7100", "to": null}}'::jsonb);
